//autogenerated don't edit
module.exports = {
    myAutogeneratedSidebar: [{
        type: 'autogenerated',
        dirName: '.', // '.' means the current docs folder
    }, ],
};


// module.exports = {
//     selfgenerated_Sidebar: [{
//             type: 'category',
//             label: 'Demo',
//             items: [
//                 'intro',
//                 'greeting',
//             ],
//         },
//         "tutorial-basics/create-a-page",
//         {
//             type: 'category',
//             label: 'Basic Tutorial',
//             items: [
//                 'tutorial-basics/create-a-blog-post',
//                 'tutorial-basics/create-a-document',
//             ],
//         },
//     ],
// };